per_listener_settings true

listener 1883
allow_anonymous false
password_file /mosquitto/config/passwords-1883

listener 1885
allow_anonymous false
password_file /mosquitto/config/passwords-1885

listener 8883
allow_anonymous false
password_file /mosquitto/config/passwords-8883
cafile /mosquitto/certs/gateway-ca.crt
certfile /mosquitto/certs/mosquitto-server.crt
keyfile /mosquitto/certs/mosquitto-server.key
require_certificate true
use_identity_as_username false
